name: djdev
channels:
 - conda-forge
 - anaconda
dependencies:
 - python>=3.6
 - numpy
 - matplotlib
 - pre-commit
 - black
 - flake8
 - isort
 - darglint
 - pytest
 - coverage
 - sphinx
 - sphinx_rtd_theme
 - sphinx-autoapi